"""Init migration

Revision ID: 4f33a4fbfc83
Revises:
Create Date: 2025-04-22 20:28:51.030435

"""
from typing import Sequence, Union

from alembic import op # type: ignore[attr-defined]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f33a4fbfc83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.String(length=2), nullable=False),
    sa.Column('suit', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rank', 'suit', name='uq_card_rank_suit')
    )
    op.create_table('game_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('is_dealer', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('player_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('current_player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_player_id'], ['game_session_player.id'], name='fk_game_session_current_player', use_alter=True),
    sa.ForeignKeyConstraint(['state_id'], ['game_state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_session_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_session_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('bet', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_session.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['player_state.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_session_id', 'player_id', name='uq_game_session_id_player_id')
    )
    op.create_table('hand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_session_player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_session_player_id'], ['game_session_player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hand_card',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hand_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['hand_id'], ['hand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hand_card')
    op.drop_table('hand')
    op.drop_table('game_session_player')
    op.drop_table('game_session')
    op.drop_table('player_state')
    op.drop_table('player')
    op.drop_table('game_state')
    op.drop_table('card')
    # ### end Alembic commands ###
