"""Init migration

Revision ID: f8606010674a
Revises:
Create Date: 2025-08-25 17:51:48.697789

"""
from typing import Sequence, Union

from alembic import op # type: ignore[attr-defined]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8606010674a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('suit', sa.String(length=1), nullable=False),
    sa.Column('rank', sa.String(length=2), nullable=False),
    sa.CheckConstraint('LENGTH(rank) >= 1 AND LENGTH(suit) <= 2', name='ck_rank'),
    sa.CheckConstraint('LENGTH(suit) = 1', name='ck_suit'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suit', 'rank')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.CheckConstraint('username IS NULL OR LENGTH(username) >= 5', name='ck_username_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('finished_at IS NULL OR finished_at >= created_at', name='check_finished_after_created_at'),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.CheckConstraint('balance >= 0', name='ck_balance_negative'),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_player',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('bet', sa.Integer(), nullable=True),
    sa.Column('is_dealer', sa.Boolean(), nullable=False),
    sa.CheckConstraint('is_dealer = False AND user_id IS NOT NULL AND bet > 0', name='ck_player'),
    sa.CheckConstraint('is_dealer = True AND user_id IS NULL AND bet IS NULL', name='ck_dealer'),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hand',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_player_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.SmallInteger(), nullable=True),
    sa.Column('is_hide', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['game_player_id'], ['game_player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hand')
    op.drop_table('game_player')
    op.drop_table('group_user')
    op.drop_table('game')
    op.drop_table('user')
    op.drop_table('group')
    op.drop_table('card')
    # ### end Alembic commands ###
