"""initial migration

Revision ID: 1cff9e4cf404
Revises:
Create Date: 2025-04-21 23:03:13.131190

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '1cff9e4cf404'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
